using HistoricalDialogueRag.Core.Application.Abstractions.Dialogue;

namespace HistoricalDialogueRag.Infrastructure.Answers;

public sealed class DevAnswerGenerator : IAnswerGenerator
{
    public Task<GeneratedAnswer> GenerateAsync(
        AnswerGenerationRequest request,
        CancellationToken cancellationToken)
    {
        if (request.ContextChunks.Count == 0)
            return Task.FromResult(new GeneratedAnswer(request.FallbackMessage));

        var top = request.ContextChunks[0];
        var metadata = top.Chunk.Metadata;
        var excerpt = NormalizeExcerpt(top.Chunk.Text, maxLength: 700);

        var answer = $"""
        DEV ANSWER: This response is generated by a local deterministic stub, not by an LLM.

        Based on the most relevant retrieved fragment, the answer should rely on "{metadata.Title}" ({metadata.Year?.ToString() ?? "unknown year"}).

        Relevant fragment:
        "{excerpt}"

        Next step: replace DevAnswerGenerator with a real LLM provider, while keeping the same IAnswerGenerator interface.
        """;

        return Task.FromResult(new GeneratedAnswer(answer.Trim()));
    }

    private static string NormalizeExcerpt(string text, int maxLength)
    {
        var normalized = text
            .Replace("\r\n", " ")
            .Replace("\n", " ")
            .Replace("\r", " ")
            .Trim();

        while (normalized.Contains("  ", StringComparison.Ordinal))
            normalized = normalized.Replace("  ", " ");

        if (normalized.Length <= maxLength)
            return normalized;

        return normalized[..maxLength].TrimEnd() + "...";
    }
}